server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active:
      - git
      - vault
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kgromov/config-demo-repo.git
          clone-on-start: true
          default-label: vault-local-config
          order: 2
        vault:
          host: localhost
          port: 8200
          scheme: http
          authentication: token
          token: hvs.VAbKI8zuHjrYFLLGIkQuhGaS
          default-key:
          order: 1
      discovery:
        enabled: false



logging:
  level:
    org.springframework.cloud: trace
