server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kgromov/config-demo-repo.git
          clone-on-start: true
          default-label: master
      discovery:
        enabled: false
